// client/src/components/Blog/PostItem.tsx
import { Link } from "react-router-dom";

type Props = {
    id: number;
    title: string;
    description: string;
}

export const PostItem = ({id, title, description}: Props) => { 
    return (
        <section>
            <img src="https://cdn.pixabay.com/photo/2023/10/12/14/41/town-8310950_1280.jpg" alt={description} height="400" width="700" />
            <div>
                <h2>{title}</h2>
                <p>{description}</p>
            </div>
            <Link to={`post/${id}`}>View Post</Link>
        </section>
    );
}

// client/src/app/Components/post/post-item/post-item.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Post } from 'src/app/Models/Post.model';
import { PostService } from 'src/app/Services/post.service';

@Component({
  selector: 'app-post-item',
  templateUrl: './post-item.component.html',
  styleUrls: ['./post-item.component.css']
})
export class PostItemComponent implements OnInit {
  @Input() post?: Post;
  constructor() {
    
  }

  ngOnInit(): void {
  }
}

<div class="container" *ngIf="post">
    <div class="row">
      <div class="col-md-4">
        <div class="card mb-3">
          <img src="https://cdn.pixabay.com/photo/2023/10/12/14/41/town-8310950_1280.jpg" class="card-img-top" alt="{{ post.title }}" height="200px" width="250px">
          <div class="card-body">
            <h5 class="card-title">{{ post.title }}</h5>
            <p class="card-text">{{ post.description }}</p>
            <button routerLink="/post/{{post.id}}" class="btn btn-primary">View Post</button>
          </div>
        </div>
      </div>
    </div>
  </div>
